PREP(cloneGroup);
PREP(helperCloneInfantry);
PREP(helperCloneVehicle);
PREP(helperSpawnInfantry);
PREP(helperSpawnVehicle);
PREP(populateMarker);
PREP(spawnGroup);
PREP(spawnGroupFromConfig);
PREP(spawnGroupPFH);
