PREP(cloneGroup);
PREP(helperCloneInfantry);
PREP(helperCloneVehicle);
PREP(helperSpawnAir);
PREP(helperSpawnArmored);
PREP(helperSpawnInfantry);
PREP(helperSpawnWheeled);
PREP(randSpawnGroup);
PREP(spawnGroup);
