PREP(elipMarkerRandomPos);
PREP(generateWaypoint);
PREP(getBuildingPos);
PREP(getNearBuildings);
PREP(markerRandomPos);
PREP(moveInBuilding);
PREP(onWaypointReached);
PREP(patrolBuilding);
PREP(recMarkerRandomPos);
